# This workflow builds and pushes the latest docker image from the master branch
name: build

on:
  push:
    branches: [ github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: lexholden/askdarcel-api:latest
      - run: echo ${{ steps.docker_build.outputs.digest }}
